### ISSUE TITLE
Wrong Job

### ISSUE THREAD

**Issue by Hiroki11x** [Hiroki11x/JMS_DeepLearning#2]
```bash
python train_imagenet.py /lustre/gi75/i75012/imagenet/absolute_train.txt /lustre/gi75/i75012/imagenet/absolute_val.txt --gpu 0
Traceback (most recent call last):
  File "train_imagenet.py", line 164, in <module>
    main()
  File "train_imagenet.py", line 160, in main
    trainer.run()
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/training/trainer.py", line 296, in run
    update()
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/training/updater.py", line 177, in update
    self.update_core()
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/training/updater.py", line 181, in update_core
    batch = self._iterators['main'].next()
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 76, in __next__
    self._invoke_prefetch()
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/iterators/multiprocess_iterator.py", line 193, in _invoke_prefetch
    data = self.dataset[index]
  File "/lustre/app/acc/chainer/2.0.0/lib/python2.7/site-packages/chainer/dataset/dataset_mixin.py", line 67, in __getitem__
    return self.get_example(index)
  File "train_imagenet.py", line 53, in get_example
    left = random.randint(0, w - crop_size - 1)
  File "/lustre/app/acc/anaconda2/4.3.0/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/lustre/app/acc/anaconda2/4.3.0/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-47, -47)
```

mpirun 抜かしたら変なことになった

**Comment by Hiroki11x** [comment]
```
$ mpirun python train_imagenet.py /lustre/gi75/i75012/imagenet/absolute_train.txt /lustre/gi75/i75012/imagenet/absolute_val.txt --gpu 0
Error: ImageNet example uses chainer.iterators.MultiprocessIterator, which works only with Python >= 3.4. 
For more details, see http://chainermn.readthedocs.io/en/master/tutorial/tips_faqs.html#using-multiprocessiterator
Error: ImageNet example uses chainer.iterators.MultiprocessIterator, which works only with Python >= 3.4. 
For more details, see http://chainermn.readthedocs.io/en/master/tutorial/tips_faqs.html#using-multiprocessiterator
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64663,1],1]
  Exit code:    255
--------------------------------------------------------------------------
```

`mpirun` つけてもダメそう
